# Generated by Django 4.2.4 on 2024-11-03 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoJardineria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HerramientaManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('numero_modelo', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialFerreteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad_prestada', models.IntegerField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_termino', models.DateField()),
                ('plantel_origen', models.CharField(choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], max_length=50)),
                ('plantel_destino', models.CharField(choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
