# Generated by Django 4.2.4 on 2024-11-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipojardineria',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='equipomantenimiento',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='herramientamanual',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='materialferreteria',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='materiallimpieza',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='equipojardineria',
            name='ubicacion',
            field=models.CharField(choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], default='Unidad Tomas Aquino', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipomantenimiento',
            name='ubicacion',
            field=models.CharField(choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], default='Unidad Tomas Aquino', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='herramientamanual',
            name='ubicacion',
            field=models.CharField(choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], default='Unidad Tomas Aquino', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialferreteria',
            name='ubicacion',
            field=models.CharField(choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], default='Unidad Tomas Aquino', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiallimpieza',
            name='ubicacion',
            field=models.CharField(choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], max_length=100),
        ),
    ]
