# Generated by Django 4.2.4 on 2024-11-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_equipojardineria_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipojardineria',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipomantenimiento',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herramientamanual',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialferreteria',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materiallimpieza',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipojardineria',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipomantenimiento',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='herramientamanual',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialferreteria',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materiallimpieza',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Unidad Tomas Aquino', 'Unidad Tomas Aquino'), ('Unidad Otay', 'Unidad Otay')], max_length=100, null=True),
        ),
    ]
