# Generated by Django 4.2.4 on 2024-11-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipojardineria_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipojardineria',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='equipomantenimiento',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='herramientamanual',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='materialferreteria',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='materiallimpieza',
            name='proveedor',
        ),
    ]
