# Generated by Django 4.2.4 on 2024-11-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_equipojardineria_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientamanual',
            name='tipo',
            field=models.CharField(default='Herramienta Manual', max_length=50),
        ),
    ]
