# Generated by Django 4.2.4 on 2024-11-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_herramientamanual_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipojardineria',
            name='tipo',
            field=models.CharField(default='Equipo de jardineria', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipomantenimiento',
            name='tipo',
            field=models.CharField(default='Equipo de mantenimiento', max_length=50),
        ),
        migrations.AlterField(
            model_name='herramientamanual',
            name='tipo',
            field=models.CharField(default='Herramienta manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='materialferreteria',
            name='tipo',
            field=models.CharField(default='Material de ferreteria', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiallimpieza',
            name='tipo',
            field=models.CharField(default='Material de limpieza', max_length=50),
        ),
    ]
