# Generated by Django 4.2.4 on 2024-11-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_equipojardineria_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
