# Generated by Django 4.2.4 on 2024-12-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prestamo_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramientamanual',
            name='numero_modelo',
        ),
        migrations.AddField(
            model_name='equipojardineria',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipomantenimiento',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='herramientamanual',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materialferreteria',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materiallimpieza',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
