# Generated by Django 4.2.4 on 2024-12-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_herramientamanual_numero_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipojardineria',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='equipomantenimiento',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='herramientamanual',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='materialferreteria',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='materiallimpieza',
            name='partida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
